add backoff to reconnect

diff --git a/rootfs/usr/bin/nord_watch b/rootfs/usr/bin/nord_watch
--- a/rootfs/usr/bin/nord_watch
+++ b/rootfs/usr/bin/nord_watch
@@ -7,7 +7,10 @@ while true; do
     nordvpn status
     nordvpn disconnect
     s6-svc -wR -t /var/run/s6/services/nordvpn
-    nord_connect
+    if ! nord_connect ; then
+      echo "Unable to connect"
+      exit 1
+    fi
   fi
 done
 
